'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto'),{pathToFileURL}=require('url');
const pw=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const engine=process.env.ENGINE_BROWSER||'chromium',htmlPath=process.argv[2]||path.resolve(__dirname,'../index.html'),out=process.env.ENGINE_TEST_OUTPUT||path.resolve(__dirname,'../test-results');
fs.mkdirSync(out,{recursive:true});
const report={engine,sha256:crypto.createHash('sha256').update(fs.readFileSync(htmlPath)).digest('hex'),checks:[],errors:[],requests:[]};
let browser,context,page;
async function check(name,fn){const start=Date.now();const evidence=await fn();report.checks.push({name,pass:true,ms:Date.now()-start,evidence});console.log('PASS',engine,name);}
async function tab(name){await page.locator('#tab-'+name).click();}
async function configure(values){
 await tab('lab');if(!await page.locator('#advanced').evaluate(e=>e.open))await page.locator('#advanced > summary').click();
 for(const [k,v] of Object.entries(values))await page.locator('#p-'+k).fill(String(v));
 await page.locator('#config-form button[type=submit]').click();
 assert.equal(await page.locator('#config-error').textContent(),'');
}
async function cycle(){const n=await page.evaluate(()=>MicroLab.state.sim.cycles);await page.locator('#one-cycle').click();await page.waitForFunction(n=>!MicroLab.state.running&&MicroLab.state.sim.cycles===n+1,n,{timeout:60000});}
async function download(button,name){const wait=page.waitForEvent('download');await page.locator(button).click();const d=await wait;const target=path.join(out,engine+'-'+name);await d.saveAs(target);return target;}
(async()=>{
 browser=await pw[engine].launch({headless:true});report.browserVersion=browser.version();context=await browser.newContext({viewport:{width:1440,height:1100},offline:engine==='chromium',acceptDownloads:true});
 await context.route(/^https?:\/\//,r=>{report.requests.push(r.request().url());return r.abort();});
 page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
 await check('Fresh file:// offline initialization',async()=>{await page.goto(pathToFileURL(htmlPath).href);await page.waitForFunction(()=>!!window.MicroLab);assert.equal(await page.title(),'微觀引擎｜Microscopic Engine Lab');assert.equal(await page.locator('#metric-theory').innerText(),'1.386');return {isolation:engine==='chromium'?'offline flag + HTTP(S) interception':'HTTP(S) interception; file navigation online flag'};});
 await check('Primary control is visible without scrolling',async()=>{const r=await page.locator('#play-top').boundingBox();assert(r.y+r.height<1100);});
 await check('Single step and pause do not add unrequested physics',async()=>{await page.locator('#single-step').click();assert.equal(await page.evaluate(()=>MicroLab.state.sim.steps),1);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>MicroLab.state.sim.steps),1);});
 await check('Cycle completion flushes actual UI and ledger',async()=>{await cycle();const r=await page.evaluate(()=>MicroLab.state.sim.records[0]);assert.equal(await page.locator('#metric-work').innerText(),r.w.toFixed(3));assert(r.w>0);await page.screenshot({path:path.join(out,engine+'-cycle.png'),fullPage:true});return {firstCycleWork:r.w};});
 await check('Manual pause flushes current state',async()=>{await page.locator('#play-top').click();await page.waitForTimeout(250);await page.locator('#play-top').click();const steps=await page.evaluate(()=>MicroLab.state.sim.steps);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>MicroLab.state.sim.steps),steps);assert((await page.locator('#lab-status').innerText()).includes('已暫停'));});
 await check('Invalid joint parameters roll back atomically',async()=>{const before=await page.evaluate(()=>JSON.stringify(MicroLab.state.sim.snapshot()));await page.locator('#p-Th').fill('.5');await page.locator('#config-form button[type=submit]').click();assert((await page.locator('#config-error').innerText()).includes('熱浴'));assert.equal(await page.evaluate(()=>JSON.stringify(MicroLab.state.sim.snapshot())),before);assert.equal(await page.locator('#p-Th').inputValue(),'3');});
 await check('Boundary and translation controls directly apply models',async()=>{await page.locator('#quick-boundary').click();assert.equal(await page.evaluate(()=>MicroLab.state.sim.p.mode),'periodic');await page.locator('#quick-move').click();assert.equal(await page.evaluate(()=>MicroLab.state.sim.p.D),4);await cycle();const r=await page.evaluate(()=>MicroLab.state.sim.records[0]);assert(Math.abs(r.wx)>.05);return {translationWork:r.wx};});
 await check('Compact configuration, warm-up exclusion and record table',async()=>{await configure({N:16,ramp:4,hold:2,burn:1,D:0});for(let j=0;j<3;j++)await cycle();const mean=await page.evaluate(()=>MicroLab.Engine.summary(MicroLab.state.sim.records.filter(r=>!r.burn).map(r=>r.w)).mean);assert.equal(await page.locator('#metric-mean').innerText(),mean.toFixed(3));await tab('notes');assert.equal(await page.locator('#cycles-table tbody tr').count(),3);});
 let saved;
 await check('CSV rows match completed cycles',async()=>{const f=await download('#cycles-csv','cycles.csv'),lines=fs.readFileSync(f,'utf8').trim().split(/\r?\n/);assert.equal(lines.length,4);assert(lines[0].includes('Wout_per_particle'));});
 await check('JSON saving and exact continuation through UI',async()=>{await page.locator('#note-p').fill('慢速每圈功較接近準靜態值。');saved=await download('#save-json','experiment.json');await tab('lab');await page.locator('#single-step').click();await page.locator('#single-step').click();const expected=await page.evaluate(()=>JSON.stringify(MicroLab.state.sim.snapshot()));await page.locator('#reset').click();await tab('notes');await page.locator('#file-input').setInputFiles(saved);await page.waitForFunction(()=>MicroLab.state.sim.cycles===3);assert.equal(await page.locator('#note-p').inputValue(),'慢速每圈功較接近準靜態值。');await tab('lab');await page.locator('#single-step').click();await page.locator('#single-step').click();assert.equal(await page.evaluate(()=>JSON.stringify(MicroLab.state.sim.snapshot())),expected);});
 await check('Malformed import preserves current experiment',async()=>{await tab('notes');const before=await page.evaluate(()=>JSON.stringify(MicroLab.state.sim.snapshot()));await page.locator('#file-input').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"format":"microscopic-engine-lab","version":"1.0.0"}')});await page.waitForFunction(()=>document.querySelector('#import-error').textContent.length>0);assert.equal(await page.evaluate(()=>JSON.stringify(MicroLab.state.sim.snapshot())),before);});
 await check('PNG exports a populated chart with metadata',async()=>{const f=await download('#save-png','chart.png');assert(fs.statSync(f).size>10000);});
 await check('POE, snapshots and clipboard fallback',async()=>{await page.locator('#fill-observation').click();assert((await page.locator('#note-o').inputValue()).includes('平均每粒子輸出功'));await page.locator('#snapshot').click();assert(await page.locator('.snapshot').count()>0);await page.locator('#copy-prompt').click();await page.waitForFunction(()=>document.querySelector('#copy-dialog').open||document.querySelector('#toast').textContent==='探究提示詞已複製。');if(await page.locator('#copy-dialog').isVisible()){assert((await page.locator('#copy-text').inputValue()).includes('二維 Langevin'));await page.locator('#copy-close').click();}});
 await check('Worker scan finishes with point table and regression',async()=>{await tab('scan');await page.locator('#scan-R').selectOption('4');await page.locator('#scan-slow').uncheck();await page.locator('#scan-start').click();await page.waitForFunction(()=>MicroLab.state.scan.status==='complete',null,{timeout:120000});assert.equal(await page.locator('#scan-table tbody tr').count(),7);assert.equal(await page.locator('#scan-progress').getAttribute('value'),'1');assert(!(await page.locator('#fit-slope').innerText()).includes('—'));await page.screenshot({path:path.join(out,engine+'-scan.png'),fullPage:true});});
 await check('Scan exports preserve independent repetitions',async()=>{const f=await download('#scan-raw','scan-raw.csv'),lines=fs.readFileSync(f,'utf8').trim().split(/\r?\n/);assert.equal(lines.length,7*4*5+1);});
 await check('Scan snapshots survive JSON roundtrip without duplicate data',async()=>{await page.locator('#scan-snapshot').click();await tab('notes');const f=await download('#save-json','scan-state.json');const data=JSON.parse(fs.readFileSync(f));const snap=data.snapshots.find(s=>s.kind==='scan');assert(snap&&snap.scan.points.length===7&&!snap.points);await page.locator('#file-input').setInputFiles(f);await page.waitForFunction(()=>document.querySelector('#toast').textContent.startsWith('載入完成'));assert.equal(await page.evaluate(()=>MicroLab.state.scan.points.length),7);await tab('scan');assert.equal(await page.locator('#scan-table tbody tr').count(),7);});
 await check('Cancellation rejects stale Worker results',async()=>{await page.locator('[data-scan=rate]').click();await page.locator('#scan-R').selectOption('20');await page.locator('#scan-start').click();await page.waitForFunction(()=>MicroLab.state.scan.points.length>=1,null,{timeout:60000});await page.locator('#scan-cancel').click();const n=await page.evaluate(()=>MicroLab.state.scan.points.length);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>MicroLab.state.scan.points.length),n);assert.equal(await page.evaluate(()=>MicroLab.state.scan.status),'cancelled');return {retainedPoints:n};});
 await check('Quick physics checks and live equilibrium distributions',async()=>{await tab('physics');await page.locator('#run-checks').click();assert.equal(await page.locator('#checks .check-status').count(),6);await page.locator('#equilibrium-preset').click();await page.waitForTimeout(300);await page.locator('#physics-play').click();assert.equal(await page.evaluate(()=>MicroLab.state.sim.p.Tc),2);assert((await page.locator('#equilibrium-values').innerText()).includes('K/N'));await page.screenshot({path:path.join(out,engine+'-physics.png'),fullPage:true});});
 await check('Tour, keyboard navigation and display mode',async()=>{await page.locator('#tour-open').click();await page.locator('#tour-next').click();await page.locator('#tour-next').click();assert.equal(await page.evaluate(()=>MicroLab.state.tab),'scan');await page.locator('#tour-close').click();await page.locator('#tab-scan').focus();await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>MicroLab.state.tab),'lab');await page.locator('#presentation').click();assert(await page.locator('body').evaluate(e=>e.classList.contains('presentation')));await page.locator('#presentation').click();});
 await check('Mobile, tablet, light theme and reduced motion',async()=>{await page.locator('#preset-base').click();await cycle();await page.locator('#theme-toggle').click();for(const width of [375,390,768,1024]){await page.setViewportSize({width,height:844});await page.waitForTimeout(120);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const r=await page.locator('#play-top').boundingBox();assert(r.y+r.height<844);if(width===390)await page.screenshot({path:path.join(out,engine+'-mobile-light.png'),fullPage:true});}await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#single-step').click();assert(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches));});
 await check('No external requests or uncaught errors',async()=>{assert.deepEqual(report.requests,[]);assert.deepEqual(report.errors,[]);});
 await context.close();
 await check('No-Worker bounded fallback produces the same experiment',async()=>{
   const c=await browser.newContext({viewport:{width:1280,height:900},offline:engine==='chromium'});await c.route(/^https?:\/\//,r=>r.abort());await c.addInitScript(()=>{window.Worker=undefined;});page=await c.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.goto(pathToFileURL(htmlPath).href);await configure({N:4,ramp:2,hold:2,burn:0});await tab('scan');await page.locator('#scan-R').selectOption('4');await page.locator('#scan-slow').uncheck();await page.locator('#scan-start').click();await page.waitForFunction(()=>MicroLab.state.scan.status==='complete',null,{timeout:120000});assert.equal(await page.locator('#scan-table tbody tr').count(),7);await c.close();
 });
 assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(out,engine+'-report.json'),JSON.stringify(report,null,2));console.log('COMPLETE',engine,report.checks.length);await browser.close();
})().catch(async e=>{console.error(e);report.failure=e.message;fs.writeFileSync(path.join(out,engine+'-report.json'),JSON.stringify(report,null,2));if(page)try{await page.screenshot({path:path.join(out,engine+'-failure.png'),fullPage:true});}catch{}if(browser)await browser.close();process.exit(1);});
